# varialbes de configuracion de docker compose
version: '3.3'

# servicios de la aplicacion
services:
# servicios de la base de datos mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: la_ceiba
      MYSQL_USER: user
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_PORT: 3308
    ports:
      - 3308:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
